### ISSUE TITLE
Run with JDK8

### ISSUE THREAD

**Issue by tonnyyi** [HotelsDotCom/bull#55]
**Is your feature request related to a problem? Please describe.**
when I try to import bull by Maven and use it in my project whose compile-level is JDK8, I got an error. Then I find out bull is compiled by JDK11.

**Describe the solution you'd like**
The features bull provided are really awesome~  So, I hope bull can provide a maven artifact like bean-utils-library-jdk8 which is compiled by JDK8. 

**Describe alternatives you've considered**

**Additional context**
My english is not that good, I hope I have described my problem clearly. WELL DONE, bull !

**Comment by antimoroma** [comment]
Hi @tonnyyi ,
maybe this could be a problem related to the version you are using. 
Try to use version [1.1.14](https://github.com/HotelsDotCom/bull/releases/tag/1.1.14) this should be the right version for JDK 8 (project have two different versions (with the same feature)for JDK8 and JDK 11).
@fborriello maybe we should make this more clear in doc / releases version?
@tonnyyi  Feel free to update the issue if this problem persists , and I think your Englis is better than mine :)

**Comment by fborriello** [comment]
Hi @tonnyyi,@antimoroma is absolutely right: the same features are provided in two different build. We did it in order to let everyone able to use BULL in their project.
As a matter of fact, this "compatibility" was not so much clear, for this reason I have: specified it into the [readme file](https://github.com/HotelsDotCom/bull#start-using), and I've created a separated [changelog](https://github.com/HotelsDotCom/bull/blob/master/CHANGELOG-JDK8.md) file. I hope this would clarify.
Thanks for your contribute, it would be really appreciated if you can provide your feedback after the library usage, this would help us to improve.
Have a nice day

P.S. thanks @antimoroma for the reply and feedback
