### ISSUE TITLE
"Generics" discover function

### ISSUE THREAD

**Issue by fborriello** [HotelsDotCom/bull#92]
**Description**

A really useful function, this project should offer, is the possibility to figure out the "Generic" type of a Collection or a Map.
This function is also required to complete the implementation of a new Map Transformer (for more details please refer to issue: #88)

**Desired solution**
The ideal solution would be the implementation of a new method: `getGenericType` that takes in input any kind of Java Collection or Map and returns its Generic type(s).

_**e.g.**_

```
List<String> v = new ArrayList<String>();
Class<?> genericClazz = getGenericType(v.getClass()); // will return: String
```

and

```
Map<String, Integer> v = new HashMap<String, Integer>();
Pair<Class<?>, Class<?>> typeMap = getGenericType(v.getClass()); // will return a Pair Class<?> keyClass = typeMap.getLeft(); // will return: String
Class<?> elemClass = typeMap.getRight(); // will return: Integer
```

**Additional context**

The method should be added into the utility class: `ReflectionUtil`

**Comment by CodeFarmer** [comment]
I may be missing something, but I suspect the example as written is not solvable due to type erasure.

If you had a collection that contained some elements, you could introspect them and guess what the generic type might have been, by trying to guess a least-generic common (super)type for the collection elements?

**Comment by polarene** [comment]
I think this might be done because generic type arguments are retained in subclasses. I'll have a try at it!

**Comment by CodeFarmer** [comment]
@antimoroma your solution is a start (if you are willing to ignore the empty list case in the first example, which @fborriello might not want).

However, you will need to look at *all* the objects in the collection, as they may not all be the same type (say ArrayList<Employee> containing objects that are Manager and Engineer classes), and find the most-specific superclass that expresses all of the elements.

**Comment by fborriello** [comment]
I do agree with you all. This function is actually required for the Map Transformation module to figure out the key and the element type to understand how to get them transformed.
The solution, you proposed, to discover the type from the first element of a collection/map could work. In case the collection/map would be empty we will return an empty List/Map.
I’ll try with that solution and then get back to you. Thanks

**Comment by polarene** [comment]
Yes @fborriello, that could be the only way to go. Keep in mind that it will be simple if you have an empty collection or map, or if the elements are homogeneous (`List<String>`). However, we could have more difficult cases if the collection has type bounds, such as `List<? extends Number>` or `List<? super Integer>`, that is if the type parameter is covariant or contravariant. 
In the first case, you'll have to inspect all the elements and find the greatest supertype (you don't know beforehand it's Number).
In the second case, you must resolve to `Object` since the upper bound is open.
The information about type parameter bounds is available through reflection.

This can get quite complicated, I know, but in the end maybe we could decide we don't want to go through all this hassle and just make Bull raise an exception if it finds a bounded type parameter.

**Comment by antimoroma** [comment]
Yes, i think it could be useful to fix some prerequisite for this implementation (or for a first implementation):
- Simply we support Collection or List without bounds (covariant, controvariant), in this case, we throw an exception.
